"use client"
import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Download, FileText } from "lucide-react"

const exportsLog = [
  { id: "EXP-201", report: "Monthly Sales Summary", format: "PDF", generatedBy: "Sales Manager", date: "Oct 17, 2026, 09:45 AM", status: "Ready" },
  { id: "EXP-202", report: "Q3 Profit & Loss", format: "PDF", generatedBy: "Accountant", date: "Oct 16, 2026, 14:20 PM", status: "Ready" },
  { id: "EXP-203", report: "Employee Directory", format: "PDF", generatedBy: "HR Dept", date: "Oct 15, 2026, 11:10 AM", status: "Ready" },
]

export default function ExportsPage() {
  return (
    <Card className="border-border/50 shadow-sm mt-0">
      <CardHeader><CardTitle>Generated Reports</CardTitle><CardDescription>System-generated PDF exports and reports.</CardDescription></CardHeader>
      <CardContent>
        <Table>
          <TableHeader><TableRow><TableHead>Export ID</TableHead><TableHead>Report Name</TableHead><TableHead>Format</TableHead><TableHead>Generated By</TableHead><TableHead>Date / Time</TableHead><TableHead /></TableRow></TableHeader>
          <TableBody>
            {exportsLog.map(e => (
              <TableRow key={e.id}>
                <TableCell className="font-mono text-xs text-muted-foreground">{e.id}</TableCell>
                <TableCell className="font-medium flex items-center gap-2"><FileText className="w-4 h-4 text-rose-500" /> {e.report}</TableCell>
                <TableCell><Badge variant="outline">{e.format}</Badge></TableCell>
                <TableCell>{e.generatedBy}</TableCell>
                <TableCell className="text-muted-foreground text-sm">{e.date}</TableCell>
                <TableCell className="text-right"><Button variant="outline" size="sm"><Download className="w-4 h-4 mr-1" /> Download</Button></TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}
